<script type="text/javascript" src="<?php echo $this->getJsUrl('tiny_mce/tiny_mce.js')?>"></script>
<div class="box-account form-new-message" style="display:none;margin-top:20px;overflow:hidden" id="ves_vendorsmessage-new-message-form">
	<div class="close-btn"><a href="javascript: void(0);" onclick="$('ves_vendorsmessage-new-message-form').fade({duration: 0.5});">Close</a></div>
	<div class="box-head header-form">
		<h2><?php echo $this->__('New Message') ?></h2>
	</div>
	<div class="box-content content-form">
    <form action="<?php echo $this->getUrl("customer/message/save") ?>" method="post" id="ves_message-new-form" enctype="multipart/form-data">
    	<div class="message-to">
    		<label for="to"><span><?php echo $this->__('Recipient ') ?><span class="required">*</span></span></label>
    		<div class="left">
	    		<span id="ves_messages_to_span"></span>
	    		<input id="ves_messages_to" class="required-entry input-text" type="hidden" value="" name="message[to]" />
	    		<input id="ves_messages_box_id" class="required-entry input-text" type="hidden" value="" name="message[message_box_id]" />
    		</div>
    		<div class="clear"></div>
    	</div>
    	<div class="message-subject">
    		<label for="subject"><span><?php echo $this->__('Subject ') ?><span class="required">*</span></span></label>
    		<div class="left">
    			<input id="ves_messages_subject" class="input-text required-entry" type="text" value="" name="message[subject]" />
    		</div>
    		<div class="clear"></div>
    	</div>
    	<div class="message-content">
	        <div>
	            <textarea class="required-entry" name="message[content]" id="ves_messages_content_message" style="width:99%;height:200px"></textarea>
				<div id="message-validate" style=""></div>
	        </div>
	        <div class="button-set">
	            <button class="button right form-button" type="button" onclick="messageform.submit(this)"><span><span><?php echo Mage::helper('vendorsmessage')->__('Send Message')?></span></span></button>
	        </div>
	        <div class="clear"></div>
	    </div>
    </form>
    </div>
</div>
<div id="ves_vendormessages_sending" class="message-sending" style="display: none;"></div>

<script type="text/javascript">
var messageform = new VarienForm('ves_message-new-form', true);
messageform.submit = function(button) {
	if(validateMessageForm()){
		 var form = this.form;
         var e = null;
         try{
            $('ves_vendorsmessage-new-message-form').hide();
        	$('ves_vendormessages_sending').update('<?php echo $this->__('Message is sending ...')?>');
         	$('ves_vendormessages_sending').show();
         	this.form.request({
         		method: 'post',
         		onSuccess: function(transport) {
               		try {
               			$('ves_vendormessages_sending').update('<?php echo $this->__('Message is sent ...')?>');
               			setTimeout(function(){$('ves_vendormessages_sending').fade({duration: 0.5});},1000);
                     }catch(e){}
         		}
             });
         } catch (e) {
         }
     }
}.bind(messageform);
function validateMessageForm(){
	if(!messageform.validator.validate()) return false;
	if(tinyMCE.get('ves_messages_content_message')){
		var content = tinyMCE.get('ves_messages_content_message').getContent(); // msg = textarea id
		if( content == "" || content == null){
			$("message-validate").show();
			$("message-validate").update('<div id="advice-required-entry-message" class="validation-advice" style="">This is a required field.</div>');
			return false;
		}
		else{
			$("message-validate").hide();
			$('ves_messages_content_message').update(content);
			return true;
			
		}
	}else{
		return true;
	}
	return false;
}

<?php if(Mage::helper('vendorsmessage')->isEnableEditor()): ?>
Event.observe(window, 'load', function() {
    tinyMCE.init({
    	forced_root_block : '',
    	force_br_newlines: true,
    	force_p_newlines: false,
        mode : "exact",
        theme : "advanced",
        width:"100%",
        height:"200px",
        strict_loading_mode : true, 
        elements : "ves_messages_content_message",
        theme_advanced_buttons1 : "bold,italic,underline,bullist,numlist,separator,outdent,indent,separator,undo,redo,separator",
        theme_advanced_buttons2 : "",
        theme_advanced_buttons3 : "",
        theme_advanced_toolbar_location : "top",
        theme_advanced_toolbar_align : "left",
        theme_advanced_path_location : "bottom",
        extended_valid_elements : "a[name|href|target|title|onclick],img[class|src|border=0|alt|title|hspace|vspace|width|height|align|onmouseover|onmouseout|name],hr[class|width|size|noshade],font[face|size|color|style],span[class|align|style]",
        theme_advanced_resize_horizontal : "true",
        theme_advanced_resizing : "true",
        apply_source_formatting : "true",
        convert_urls : "false",
        force_br_newlines : "true",
        doctype : '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">' 
    });  
});
<?php endif; ?>
</script>
