<script type="text/javascript" src="<?php echo $this->getJsUrl('tiny_mce/tiny_mce.js')?>"></script>
<div class="reply-message" id="reply-message-button">
	<button class="button center reply-message-button"  type="button" onclick="showFormReply()" ><span><span><?php echo Mage::helper('vendorsmessage')->__('Reply')?></span></span></button>
</div>
<div class="form-reply" style="display:none" id="form-reply-message">
    <form action="<?php echo $this->getUrlReply() ?>" method="post" id="message-reply-form" enctype="multipart/form-data">
    	<div class="message-content">
	        <div>
	            <textarea class="required-entry" name="message[content]" id="content_message" style="width:99%;height:200px"></textarea>
				<div id="message-validate" style=""></div>
	        </div>
	        <div class="button-set">
	           <button class="button right form-button" type="button"  onclick="if(messageform.validator && messageform.validator.validate()){ submitMessage();}"><span><span><?php echo Mage::helper('vendorsmessage')->__('Send Message')?></span></span></button>
	        </div>
	        <div class="clear"></div>
	    </div>
    </form>
     <script type="text/javascript">
   	 var messageform = new VarienForm('message-reply-form', true);
    </script>
</div>
<script type="text/javascript">

function submitMessage(){
	if(tinyMCE.get('content_message')){
		var content = tinyMCE.get('content_message').getContent(); // msg = textarea id
		if( content == "" || content == null){
			//alert("test");
			$("message-validate").show();
			$("message-validate").update('<div id="advice-required-entry-message" class="validation-advice" style="">This is a required field.</div>');
			return false;
		}
		else{
			$("message-validate").hide();
			if(content!=""){ $('message-reply-form').submit();}
			
		}
	}
	else{
		$('message-reply-form').submit();
	}
}

function showFormReply(){
	$('form-reply-message').show();
	$('reply-message-button').hide();
	Effect.ScrollTo("form-reply-message", { duration: 1.0 });
}
<?php if(Mage::helper('vendorsmessage')->isEnableEditor()): ?>
Event.observe(window, 'load', function() {
    tinyMCE.init({
    	forced_root_block : '',
    	force_br_newlines: true,
    	force_p_newlines: false,
        mode : "exact",
        theme : "advanced",
        width:"100%",
        height:"300px",
        strict_loading_mode : true, 
        elements : "content_message",
        theme_advanced_buttons1 : "bold,italic,underline,bullist,numlist,separator,outdent,indent,separator,undo,redo,separator",
        theme_advanced_buttons2 : "",
        theme_advanced_buttons3 : "",
        theme_advanced_toolbar_location : "top",
        theme_advanced_toolbar_align : "left",
        theme_advanced_path_location : "bottom",
        extended_valid_elements : "a[name|href|target|title|onclick],img[class|src|border=0|alt|title|hspace|vspace|width|height|align|onmouseover|onmouseout|name],hr[class|width|size|noshade],font[face|size|color|style],span[class|align|style]",
        theme_advanced_resize_horizontal : "true",
        theme_advanced_resizing : "true",
        apply_source_formatting : "true",
        convert_urls : "false",
        force_br_newlines : "true",
        //content_css :"<?php // echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>frontend/default/default/css/ves_helpdesk/tinymce/style.css",
        doctype : '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">' 
    });  
});
<?php endif; ?>
</script>
