<div class="account-login">
	<div id="loginbox">
		<?php echo $this->getMessagesBlock()->getGroupedHtml(); ?>
		<form action="<?php echo $this->getUrl('*/*/resetpasswordpost', array('_query' => array('id' => $this->getVendorId(), 'token' => $this->getResetPasswordLinkToken()))); ?>" method="post" id="form-validate">
			<div class="control-group normal_text">
		 		<h3><?php echo $this->__('Reset a Password'); ?></h3>
			</div>
			<div class="control-group">
				<div class="controls">
					<div class="main_input_box">
						<span class="add-on"><i class="icon-lock"></i></span><input type="password" class="input-text required-entry validate-password" name="password" id="password" placeholder="<?php echo $this->__('New password') ?>"/>
					</div>
				</div>
			</div>
			<div class="control-group">
				<div class="controls">
					<div class="main_input_box">
						<span class="add-on"><i class="icon-lock"></i></span><input type="password" class="input-text required-entry validate-cpassword" name="confirmation" id="confirmation" placeholder="<?php echo $this->__('Confirm New Password') ?>" />
					</div>
				</div>
			</div>
		    <div class="form-actions">
		        <span class="pull-right"><button type="submit" title="<?php echo $this->__('Reset a Password'); ?>" class="btn btn-info"><span><span><?php echo $this->__('Reset a Password'); ?></span></span></button></span>
		    </div>
		</form>
		<script type="text/javascript">
		/*<![CDATA[*/
		    var dataForm = new VarienForm('form-validate', true);
		/*]]>*/
		</script>
	</div>
</div>