<?php if($this->getTitle()): ?>
    <h3><?php echo $this->getTitle() ?></h3>
<?php endif ?>
<?php if(!empty($tabs)): ?>
<ul id="<?php echo $this->getId() ?>" class="tabs">
<?php foreach ($tabs as $_tab): ?>
<?php if (!$this->canShowTab($_tab)): continue;  endif; ?>
    <li>
        <a href="<?php if(!$_tab->getActive()) {echo $_tab->getUrl();}else {echo "javascript: void(0);";} ?>" id="<?php echo $_tab->getTabId() ?>" name="<?php echo $_tab->getTabId() ?>" title="<?php echo $_tab->getTitle() ?>" class="tab-item-link<?php if($_tab->getActive()):?> active<?php endif;?>">
            <span><?php echo $_tab->getLabel(); ?></span>
        </a>
    </li>
<?php endforeach; ?>
</ul>
<?php endif; ?>