<?php $count = 0;?>
<?php foreach($this->getItemsByVendor() as $key=>$items): ?>
<?php if(!sizeof($items)) continue;?>
<div class="clearer cart-vendor<?php if($count ==0):?> cart-vendor-first<?php endif;?><?php if(($count+1)==$this->getItemCount()):?> cart-vendor-end<?php endif;?> cart-<?php echo $key;?>-container">
	<?php $vendor = $this->getVendor($key);?>
	<h3><?php echo $vendor->getTitle();?></h3>
	<table id="shopping-cart-table-<?php echo $key;?>" class="data-table cart-table">
		<col width="1" />
		<col />
		<col width="1" />
	<?php if ($this->helper('wishlist')->isAllowInCart()) : ?>
		<col width="1" />
	<?php endif ?>
	<?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
		<col width="1" />
	<?php endif; ?>
	<?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
		<col width="1" />
	<?php endif; ?>
		<col width="1" />
	<?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
		<col width="1" />
	<?php endif; ?>
	<?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
		<col width="1" />
	<?php endif; ?>
		<col width="1" />
	
	<?php $mergedCells = ($this->helper('tax')->displayCartBothPrices() ? 2 : 1); ?>
		<thead>
			<tr>
				<th rowspan="<?php echo $mergedCells; ?>">&nbsp;</th>
				<th rowspan="<?php echo $mergedCells; ?>"><span class="nobr"><?php echo $this->__('Product Name') ?></span></th>
				<th rowspan="<?php echo $mergedCells; ?>"></th>
				<?php if ($this->helper('wishlist')->isAllowInCart()) : ?>
				<th rowspan="<?php echo $mergedCells; ?>" class="a-center"><span class="nobr"><?php echo $this->__('Move to Wishlist') ?></span></th>
				<?php endif ?>
				<th class="a-center" colspan="<?php echo $mergedCells; ?>"><span class="nobr"><?php echo $this->__('Unit Price') ?></span></th>
				<th rowspan="<?php echo $mergedCells; ?>" class="a-center"><?php echo $this->__('Qty') ?></th>
				<th class="a-center" colspan="<?php echo $mergedCells; ?>"><?php echo $this->__('Subtotal') ?></th>
				<th rowspan="<?php echo $mergedCells; ?>" class="a-center">&nbsp;</th>
			</tr>
			<?php if ($this->helper('tax')->displayCartBothPrices()): ?>
			<tr>
				<th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
				<th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
				<th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
				<th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
			</tr>
			<?php endif; ?>
		</thead>
		<tbody>
			<?php foreach($items as $_item): ?>
				<?php echo $this->getItemHtml($_item) ?>
				<?php $count ++;?>
			<?php endforeach;?>
		</tbody>
		<tfoot>
			<tr>
				<td colspan="50" class="a-right">
					<button type="button" name="update_cart_action" onclick="setLocation('<?php echo $this->getClearCartUrlByVendor($key)?>')" title="<?php echo $this->__('Clear Shopping Cart'); ?>" class="button btn-empty left" id="empty_cart_button"><span><span><?php echo $this->__('Clear Shopping Cart'); ?></span></span></button>
					<button type="submit" name="update_cart_action" value="update_qty" title="<?php echo $this->__('Update Shopping Cart'); ?>" class="button btn-update left"><span><span><?php echo $this->__('Update Shopping Cart'); ?></span></span></button>
					<button type="button" title="<?php echo $this->__('Process to Checkout') ?>" class="button right" onclick="setLocation('<?php echo $this->getProcessCheckoutUrl($key) ?>')"><span><span><?php echo $this->__('Process to Checkout') ?></span></span></button>
					<!--[if lt IE 8]>
					<input type="hidden" id="update_cart_action_container" />
					<script type="text/javascript">
					//<![CDATA[
						Event.observe(window, 'load', function()
						{
							// Internet Explorer (lt 8) does not support value attribute in button elements
							$emptyCartButton = $('empty_cart_button');
							$cartActionContainer = $('update_cart_action_container');
							if ($emptyCartButton && $cartActionContainer) {
								Event.observe($emptyCartButton, 'click', function()
								{
									$emptyCartButton.setAttribute('name', 'update_cart_action_temp');
									$cartActionContainer.setAttribute('name', 'update_cart_action');
									$cartActionContainer.setValue('empty_cart');
								});
							}
	
						});
					//]]>
					</script>
					<![endif]-->
				</td>
			</tr>
		</tfoot>
		
	</table>
</div>
<script type="text/javascript">decorateTable('shopping-cart-table')</script>
<?php endforeach ?>