<?php if(!empty($links)): ?>
<div class="breadcrumb-container">
	<ul class="breadcrumbs">
	    <?php $_size=count($links); ?>
	    <?php foreach ($links as $_index=>$_link): ?>
	    <li class="<?php echo $_link['class']?>">
	        <?php if(empty($_link['url'])): ?>
	            <?php if($_index!=$_size-1): ?>
	                <span><?php echo $this->htmlEscape($_link['label']) ?></span>
	            <?php else: ?>
	                <strong><?php echo $this->htmlEscape($_link['label']) ?></strong>
	            <?php endif; ?>
	        <?php else: ?>
	            <a href="<?php echo $_link['url'] ?>" title="<?php echo $this->htmlEscape($_link['title']) ?>"><?php echo $this->htmlEscape($_link['label']) ?></a>
	        <?php endif; ?>
	        <?php if($_index!=$_size-1): ?>
	        <?php endif; ?>
	    </li>
	    <?php endforeach; ?>
	</ul>
</div>
<?php endif; ?>
